# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e3134ce1494ba1a2229bfa224e3e9bfdca6c1e7b9cf0b7f5b3591e69eb9198827826ccf8baed13994a3c1a528a91e7fcf243a1b6e41aa1a5347f36576eecbb4

test:
  secret_key_base: 5498cb4ab4738e8cf68eb1a4b7f8489d682ae3d2db3ec73b1fbb655b7514af61278a32941326ded27f47612d7d8b5b5f90e3260e765dbd21a8d7c5736a7c2cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
